
ALTER TABLE users ADD COLUMN first_name TEXT;
ALTER TABLE users ADD COLUMN last_name TEXT;
ALTER TABLE users ADD COLUMN zip TEXT;
ALTER TABLE users ADD COLUMN allow_email BOOLEAN;
ALTER TABLE users ADD COLUMN updated BOOLEAN DEFAULT FALSE;
